### ISSUE TITLE
Ability to disable crop?

### ISSUE THREAD

**Issue by jeffalo** [Dullage/eyelign#18]
Hey, this is a really cool project and it's pretty much exactly what I was looking for.. Thanks!

If you are still working on it, would it be possible to add a mode where cropping the image is disabled, and the image is instead rotated/scaled/panned on a black background? My photos have a consistent aspect ratio, and my eyes are roughly in the same place across each photos, so I would prefer retaining everything in the photos to having the images be cropped really close to my face.

I'm not sure if that explanation was clear, but here is a video demonstrating something similar to what I was looking for.. https://www.youtube.com/watch?v=65nfbW-27ps

**Comment by dullage** [comment]
Hey @jeffalo, good to hear someone else is finding this useful. 

It's been a while since I worked on this last so I'm a little fuzzy on the details but have you tried playing with the `--eye-width-pct` parameter along with `--output-width` and `--output-height` as I _think_ this might already be possible.

If not let me know as it might be a small change.

**Comment by jeffalo** [comment]
Setting the eye-width-pct to around 10 works perfectly! Thank you so much! :)
