### ISSUE TITLE
Help Please 

### ISSUE THREAD

**Issue by Stefannzbg** [Dullage/eyelign#20]
I saw the response you left someone else on GitHub last week. I tried to follow your response by pasting this in Ubuntu and having already downloaded your Eyeallign image to docker

docker run -it --rm -v "C:\Users\User\Downloads\Input:/input" -v "C:\Users\User\Downloads/Output:/output" dullage/eyelign:latest
docker

What you see above is I copied the paths and pasted them rather than what you had 

docker run -it --rm -v "/input/folder/path:/input" -v "/output/folder/path:/output" dullage/eyelign:latest

I have created a “Input” folder in my downloads folder with the images and an "Output” folder in the downloads folder on my windows computer.

I get this error 
docker: Error response from daemon: invalid mode: /input.

What am I doing wrong? 

Kind Regards, 
Stefan

**Comment by dullage** [comment]
Hi @Stefannzbg,

I'll try and help if I can. 

You say you're running this on Ubuntu but those look like Windows paths `C:\...`. Perhaps you're using Ubuntu on WSL?

In any case, if you're machine is a Windows machine then you can run eyelign directly from there rather than using Ubuntu. You just need to download Docker Desktop for Windows.

One other note is that the Windows paths you mention won't work in Ubuntu. Party because they won't exist and party because you'd need to use forward slashes rather than backslashes. But none of this matters if you switch to using Docker Desktop for Windows.

**Comment by Stefannzbg** [comment]
Yes I am on a windows laptop. I have ubuntu and docker desktop open at the moment. 

I have your image here. 

How do I do the next steps? 

![image](https://github.com/dullage/eyelign/assets/137376164/8553979f-c326-4aa6-bd10-d2422a8e0a3f)

**Comment by dullage** [comment]
Try running the commands from Windows rather than Ubuntu. Use something like Command Prompt or Powershell.

If that doesn't work post back here with the exact command you used and the problem you get.

**Comment by Stefannzbg** [comment]
Thank you so much! It worked , how exciting! 
I even was able to figure out the ffmpeg on windows (I took quite a while though)

Good luck to you and your family 

Stefan 
New Zealand
